### PR TITLE
JIRA integration

### PR DESCRIPTION
**Pull request by Gby56**
Hi Seek !
I discovered Listo through the blogpost and was instantly interested, but couldn't find a JIRA integration, so I made one !
For now, it will create a simple Work item titled `[<level> Risk] Listo: feature name` and attach subtasks, adds a label `listo_<high,medium,low>` and tags the user, and assigns to the configured user for the API.
I struggled a bit to get a checklist that looked okay, but it's a bullet point with checkmarks ✅  and warning signs ⚠️ 
It might be interesting to subdivide the subtasks (which are Modules) by Categories ? Tell me what you think !

This adds the following env variables:

- TRELLO_JIRA_MODE (set to JIRA or TRELLO)
- JIRA_HOST (just the host, no protocol)
- JIRA_USER (user to connect to the API & assign+report issues to)
- JIRA_PASSWORD 
- JIRA_PROJECT (which Jira project to create the listo issues to)

To illustrate what the descriptions look like
image

image

This would also require updating the readmes to explain it 👼

### CODE REVIEW

**Comment by Gby56** [comment]
@bertonjulian What do you think ? Anything I should add/remove to the PR ?

**Comment by Gby56** [comment]
Is the project a bit dead ? :(
I'm quite happy to work on it, I have been adding a Maturity Step in my fork for example

**Comment by bertonjulian** [comment]
Hey Gabriel,

Sorry for the late reply and thanks for contributing to Listo! I don't have
time to work on Listo atm as I'm no longer using it for my day job
unfortunately :( So don't let my lack of approval stand in the way of
progress!

What I would say after a very quick look at the changes:

   - It adds Jira and the Maturity Step in the same PR, so it might be
   worth splitting them out into separate PR's to make it easier to review /
   test the changes? The Jira integration is optional which will make it
   easier to approve, but the Maturity step adds a change for all users of
   Listo which might affect some flows.
   - Regarding the Maturity step, is there any reason its a separate step
   and not a drop down within the projectMeta step? I remember trying to
   design the flow so that there are as few steps as possible. But let us know
   if you think its better as a separate step. Either way, it's good
   information to have.
   - I would add a description to the PR saying how you tested the changes,
   given we dont have tests for Listo. This will also give others confidence
   the changes will not introduce any bugs. Ideally we should add some tests,
   but we never got around to it :(

Thanks

Julian

**Comment by Gby56** [comment]
Hi Julian !
No problem, sorry I saw you left seek but I thought maybe it was still active in some way, it's a great tool and I really liked goSDL but this is even better :)

Totally agree on the PR split, I completely forgot I pushed everything on master in my fork, I might need to revert and put changes in separate branches.

I'm not a React wizard at all so I just copied the project meta step for the maturity, I had no clue how to add a drop down and adapt the YAML structure 😅 The dream would be to change which questions or steps appear, depending on Maturity, to only ask for high level or low level details. You could even have a toggle to show/hide the questions from other steps.

I was playing with cloudformation and the deployment, so I left the code a bit but I'll dive back in.


By the way, you probably know React much more than me, I was trying to change the front end text to match which issue tracker was configured, Jira or Trello. I use a REACT_APP environment variable, but that's going to be baked into the container, since the front end bakes it in? I didn't know how the backend environnement variables could reflect that in the front without building it in.

**Pull request closed without merging**
